### ISSUE TITLE
Wrong total size reported

### ISSUE THREAD

**Issue by kekh** [abbat/ekstertera#6]
Hi,

As shown in the image below, the total size of the account is wrongly reported. 10Go should be displayed instead of 1Go, I'm using the free Yandex account and after triple check on their website I see indeed 10GB of space...

Maybe a problem on their side (with API)?

![Status bar](http://imgur.com/W5IDVKcl.png)

**Comment by abbat** [comment]
Would you show output from console command:

```
$ curl -H 'Authorization: OAuth XXXXXXX' 'https://cloud-api.yandex.net/v1/disk/'
```

Where XXXXXXX is your OAuth token (Attention! Dont post/show your token!)

**Comment by kekh** [comment]
Here is the output:

``` json
{"trash_size":11058709,"total_space":10737418240,"used_space":54711507,"system_folders":{"applications":"disk:/Applications","downloads":"disk:/Downloads/"}}
```

**Comment by abbat** [comment]
Fixed, Thanks!

**Comment by kekh** [comment]
Great, thanks for your reactivity!
