### ISSUE TITLE
Программа выгружает файл на Диск два раза

### ISSUE THREAD

**Issue by DX37** [abbat/ekstertera#8]
Собственно вот.  Выгружаю файл размером ~350 МБ. По окончании программа начинает загрузку ещё раз. Если прервать загрузку, будь то первую или повторную - файл не появится на Диске.

**Comment by abbat** [comment]
Наиболее вероятная причина - в процессе загрузки произошла ошибка. В этом случае программа попытается осуществить повторную загрузку файла. На данный момент установлено 5 повторных попыток загрузки после чего программа отобразит ошибку. Пока данный параметр не настраивается.

**Comment by abbat** [comment]
TODO: вывести максимальное количество попыток в настройки.

**Comment by DX37** [comment]
Что интересно - так происходит именно два раза: загрузка, повторная загрузка. А если выгружать через `ydcmd` - всё нормально и по времени выгружается как один раз.

**Comment by DX37** [comment]
Может есть какой-то супер режим дебага?

**Comment by abbat** [comment]
На данный момент нет. Можно попробовать поправить код следующим образом:

```
--- a/src/utils/api.cpp
+++ b/src/utils/api.cpp
@@ -350,7 +350,7 @@ EteraAPI::EteraAPI(QObject* parent, quint64 id) : QObject(parent)
     m_ensure      = eitUnknown;
 
     m_retry       = 0;
-    m_max_retries = 5; /* TODO: #2 */
+    m_max_retries = 0; /* TODO: #2 */
 
     m_tick      = 0;
     m_prev_tick = 0;
```

В этом случае при возникновении ошибки операция прервется и будет отображен текст ошибки.

**Comment by abbat** [comment]
Закрыто за отсутствием активности.
